//
//  Visit+CoreDataProperties.swift
//  Keel
//
//  Generated by Core Data
//

import Foundation
import CoreData

extension Visit {

    @nonobjc public class func fetchRequest() -> NSFetchRequest<Visit> {
        return NSFetchRequest<Visit>(entityName: "Visit")
    }

    @NSManaged public var id: UUID?
    @NSManaged public var lat: Double
    @NSManaged public var lon: Double
    @NSManaged public var arrival: Date?
    @NSManaged public var departure: Date?
    @NSManaged public var merchant: String?
    @NSManaged public var recommendedCard: String?

}

extension Visit : Identifiable {

}
